### ISSUE TITLE
Notice: I Am Totally Alive

### ISSUE THREAD

**Issue by peppermilldetective** [Xeavior/Stringless#1]
Just wanted to update everyone: I am alive.

Currently have been having health problems. I was sick the entirety of the week before (2/6 - 2/10) with a cold and on and off stomach problems. This went away between Saturday and Sunday. Monday and Tuesday were spent weak and without energy. Taking a short shower left me without breath and made it hard to move. Wednesday through Friday were spent dealing with a stomach virus.

Currently feeling like crap due to not being able to do anything, but I do plan on continuing. Current ideas I am wishing to pass on:
    * 3 "generic" npc sprites (no faces, generic manequins, thinking of how to make them different)
    * Item shop npc sprite (face is a bag)
    * Weapon shop npc sprite (face is a sword)
    * Armor shop npc sprite (face is an anvil)
    * Bank/Item Holder/Thing npc sprite (face is a box, head is a box... er.... jack-in-the-box if feeling fancy)
    * Large enemy (Tank or heavy hitter)
    * Medium enemy (basic sword wielder?)
    * Medium enemy (basic ranged wielder?)
    * Small enemy (Dagger-wielders?)

Current problem: how do you want me to organize everything? For enemies/npcs, should I save space and put everything on labeled sheets? Or should I separate on a sprite-by-sprite basis? Also, for folder organization (assuming separations):
    * Sprites
        * MC
        * NPC
            * genericnpc1
            * genericnpc2
            * genericnpc3
            * itemshop
            * weaponshop
            * armorshop
            * boxshop
        * Enemies
            * lrg_enemy
            * med_enemy_swd
            * med_enemy_arc
            * sml_enemy

Without separations, everything becomes as close to one sheet as possible, but separated based on character class (npc vs enemy).

Also, somewhat minor, yet not minor, thing. It's been bothering me. DO THEY HAVE NOSES? For the love of God, are we giving them noses? Or are we just gonna say that they are painted-on noses? This has been bothering me for the past two weeks.

Sincerely,
-Jarrett Locke

**Comment by Xeavior** [comment]
Hey Jarrett,

I'm sorry you've been feeling so bad lately! We have made many accomplishments in scripting some of the puzzle mechanics for the game while you were away. 

I love your ideas for each of the Npcs presented. To stick with the carnival-esque theme, I think the heavy enemies should be strong men that hit hard with there hand nubs, the medium enemies could possibly be clowns with water flower guns and sword swallowers that fight with rapiers, and I agree the small ones should have daggers of some sort.

As for separation, make a sprite sheet for each of the characters and enemies(so sprite by sprite and orientation), I believe that will make it easier on Josh.

The characters will not have noses but they will have painted on noses, to clear your head. As a final note, will we need a bank? Items that the player can get can just be equipped and used but no inventory will be used, I'll let you guys decide.

Also, Jarrett if you want to take a break from sprite making, feel free to make a script for an NPC or enemy (enemy more preferred).

Everyone,

We will be meeting tomorrow shortly to organize what all will be done by each of us by Wednesday.

Have a great Sunday!
